//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.24 at 10:47:05 PM MDT 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateWorkItemWithPartiesRequest }
     * 
     */
    public CreateWorkItemWithPartiesRequest createCreateWorkItemWithPartiesRequest() {
        return new CreateWorkItemWithPartiesRequest();
    }

    /**
     * Create an instance of {@link CreateWorkItemWithPartiesRequest.Parties }
     * 
     */
    public CreateWorkItemWithPartiesRequest.Parties createCreateWorkItemWithPartiesRequestParties() {
        return new CreateWorkItemWithPartiesRequest.Parties();
    }

    /**
     * Create an instance of {@link ToLowercaseRequest }
     * 
     */
    public ToLowercaseRequest createToLowercaseRequest() {
        return new ToLowercaseRequest();
    }

    /**
     * Create an instance of {@link GenerateUIDRequest }
     * 
     */
    public GenerateUIDRequest createGenerateUIDRequest() {
        return new GenerateUIDRequest();
    }

    /**
     * Create an instance of {@link GenerateUIDResponse }
     * 
     */
    public GenerateUIDResponse createGenerateUIDResponse() {
        return new GenerateUIDResponse();
    }

    /**
     * Create an instance of {@link ReverseStringRequest }
     * 
     */
    public ReverseStringRequest createReverseStringRequest() {
        return new ReverseStringRequest();
    }

    /**
     * Create an instance of {@link RandomNumberResponse }
     * 
     */
    public RandomNumberResponse createRandomNumberResponse() {
        return new RandomNumberResponse();
    }

    /**
     * Create an instance of {@link RandomStringRequest }
     * 
     */
    public RandomStringRequest createRandomStringRequest() {
        return new RandomStringRequest();
    }

    /**
     * Create an instance of {@link ToLowercaseResponse }
     * 
     */
    public ToLowercaseResponse createToLowercaseResponse() {
        return new ToLowercaseResponse();
    }

    /**
     * Create an instance of {@link RandomNumberRequest }
     * 
     */
    public RandomNumberRequest createRandomNumberRequest() {
        return new RandomNumberRequest();
    }

    /**
     * Create an instance of {@link CreateWorkItemWithPartiesResponse }
     * 
     */
    public CreateWorkItemWithPartiesResponse createCreateWorkItemWithPartiesResponse() {
        return new CreateWorkItemWithPartiesResponse();
    }

    /**
     * Create an instance of {@link ToUppercaseResponse }
     * 
     */
    public ToUppercaseResponse createToUppercaseResponse() {
        return new ToUppercaseResponse();
    }

    /**
     * Create an instance of {@link GetCountryRequest }
     * 
     */
    public GetCountryRequest createGetCountryRequest() {
        return new GetCountryRequest();
    }

    /**
     * Create an instance of {@link ReverseStringResponse }
     * 
     */
    public ReverseStringResponse createReverseStringResponse() {
        return new ReverseStringResponse();
    }

    /**
     * Create an instance of {@link RandomStringResponse }
     * 
     */
    public RandomStringResponse createRandomStringResponse() {
        return new RandomStringResponse();
    }

    /**
     * Create an instance of {@link GetCountryResponse }
     * 
     */
    public GetCountryResponse createGetCountryResponse() {
        return new GetCountryResponse();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link ToUppercaseRequest }
     * 
     */
    public ToUppercaseRequest createToUppercaseRequest() {
        return new ToUppercaseRequest();
    }

    /**
     * Create an instance of {@link CreateWorkItemWithPartiesRequest.Parties.Party1 }
     * 
     */
    public CreateWorkItemWithPartiesRequest.Parties.Party1 createCreateWorkItemWithPartiesRequestPartiesParty1() {
        return new CreateWorkItemWithPartiesRequest.Parties.Party1();
    }

    /**
     * Create an instance of {@link CreateWorkItemWithPartiesRequest.Parties.Party2 }
     * 
     */
    public CreateWorkItemWithPartiesRequest.Parties.Party2 createCreateWorkItemWithPartiesRequestPartiesParty2() {
        return new CreateWorkItemWithPartiesRequest.Parties.Party2();
    }

    /**
     * Create an instance of {@link CreateWorkItemWithPartiesRequest.Parties.Party3 }
     * 
     */
    public CreateWorkItemWithPartiesRequest.Parties.Party3 createCreateWorkItemWithPartiesRequestPartiesParty3() {
        return new CreateWorkItemWithPartiesRequest.Parties.Party3();
    }

    /**
     * Create an instance of {@link CreateWorkItemWithPartiesRequest.Parties.Party4 }
     * 
     */
    public CreateWorkItemWithPartiesRequest.Parties.Party4 createCreateWorkItemWithPartiesRequestPartiesParty4() {
        return new CreateWorkItemWithPartiesRequest.Parties.Party4();
    }

    /**
     * Create an instance of {@link CreateWorkItemWithPartiesRequest.Parties.Party5 }
     * 
     */
    public CreateWorkItemWithPartiesRequest.Parties.Party5 createCreateWorkItemWithPartiesRequestPartiesParty5() {
        return new CreateWorkItemWithPartiesRequest.Parties.Party5();
    }

    /**
     * Create an instance of {@link CreateWorkItemWithPartiesRequest.Parties.Party6 }
     * 
     */
    public CreateWorkItemWithPartiesRequest.Parties.Party6 createCreateWorkItemWithPartiesRequestPartiesParty6() {
        return new CreateWorkItemWithPartiesRequest.Parties.Party6();
    }

    /**
     * Create an instance of {@link CreateWorkItemWithPartiesRequest.Parties.Party7 }
     * 
     */
    public CreateWorkItemWithPartiesRequest.Parties.Party7 createCreateWorkItemWithPartiesRequestPartiesParty7() {
        return new CreateWorkItemWithPartiesRequest.Parties.Party7();
    }

    /**
     * Create an instance of {@link CreateWorkItemWithPartiesRequest.Parties.Party8 }
     * 
     */
    public CreateWorkItemWithPartiesRequest.Parties.Party8 createCreateWorkItemWithPartiesRequestPartiesParty8() {
        return new CreateWorkItemWithPartiesRequest.Parties.Party8();
    }

}
